In [2]:
import pandas as pd
import sqlite3 
# creating database connection
conn=sqlite3.connect('inventory.db')

In [3]:
tables=pd.read_sql_query("Select name from sqlite_master where type='table'",conn)
tables

                   name
0       begin_inventory
1         end_inventory
2              purchase
3        purchase_price
4                 sales
5                vendor
6  vendor_sales_summary

In [4]:
tables = tables[~tables['name'].str.contains(r'[^\w\d_]')]

In [5]:
for table in tables['name']:
    print('_'*50, f'{table}', '_'*50)
    query = f'SELECT COUNT(*) as count FROM "{table}"'  # Safely quote table name
    print('count of records:', pd.read_sql(query, conn)['count'].values[0])
    display(pd.read_sql(f'SELECT * FROM "{table}"', conn))

__________________________________________________ begin_inventory __________________________________________________
count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,01-01-2024
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,01-01-2024
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,01-01-2024
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,01-01-2024
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,01-01-2024
...,...,...,...,...,...,...,...,...,...
206524,79_BALLYMENA_46985,79,BALLYMENA,46985,Rodney Strong Cab Svgn Alexa,750mL,13,22.99,01-01-2024
206525,79_BALLYMENA_47014,79,BALLYMENA,47014,Juan Gil Jumilla Rd,750mL,13,13.99,01-01-2024
206526,79_BALLYMENA_47090,79,BALLYMENA,47090,Napa Cellars Cab Svgn Napa,750mL,19,23.99,01-01-2024
206527,79_BALLYMENA_90011,79,BALLYMENA,90011,Ch Pichon Longville 12 Pauil,750mL,12,144.99,01-01-2024
206528,79_BALLYMENA_90089,79,BALLYMENA,90089,Ch Lynch Bages 12 Pauillac,750mL,24,119.99,01-01-2024

__________________________________________________ end_inventory __________________________________________________
count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,31-12-2024
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,31-12-2024
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,31-12-2024
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,31-12-2024
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,31-12-2024
...,...,...,...,...,...,...,...,...,...
224484,81_PEMBROKE_90087,81,PEMBROKE,90087,Ch Mouton Rothschild 12 Paui,750mL,3,469.99,31-12-2024
224485,81_PEMBROKE_90088,81,PEMBROKE,90088,Ch Le Petite Mouton 12 Pauil,750mL,3,134.99,31-12-2024
224486,81_PEMBROKE_90089,81,PEMBROKE,90089,Ch Lynch Bages 12 Pauillac,750mL,3,119.99,31-12-2024
224487,81_PEMBROKE_90090,81,PEMBROKE,90090,Ch Lafite Rothschild 12,750mL,3,649.99,31-12-2024
224488,81_PEMBROKE_90604,81,PEMBROKE,90604,Ch Lynch Bages Pauilac,750mL,2,119.99,31-12-2024

__________________________________________________ purchase __________________________________________________
count of records: 1048575

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,21-12-2023,02-01-2024,04-01-2024,16-02-2024,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,01-01-2024,07-01-2024,21-02-2024,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,02-01-2024,07-01-2024,21-02-2024,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,01-01-2024,07-01-2024,21-02-2024,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,24-12-2023,02-01-2024,09-01-2024,16-02-2024,21.32,5,106.60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,74_PAENTMARWY_8450,74,8450,E & J Brandy VS,1.75L,3252,E & J GALLO WINERY,10781,22-06-2024,27-06-2024,07-07-2024,08-08-2024,13.86,5,69.30,1
1048571,53_HILLFAR_7374,53,7374,New Amsterdam Mango Vodka,750mL,3252,E & J GALLO WINERY,10781,22-06-2024,29-06-2024,07-07-2024,08-08-2024,6.86,12,82.32,1
1048572,76_DONCASTER_18106,76,18106,Barefoot Cellars Pink Moscat,1.5L,3252,E & J GALLO WINERY,10781,22-06-2024,29-06-2024,07-07-2024,08-08-2024,7.14,4,28.56,2
1048573,17_OLDHAM_10421,17,10421,Barefoot Moscato Cal,1.5L,3252,E & J GALLO WINERY,10781,22-06-2024,30-06-2024,07-07-2024,08-08-2024,5.90,5,29.50,2
1048574,34_PITMERDEN_6361,34,6361,Totts Extra Dry,750mL,3252,E & J GALLO WINERY,10781,22-06-2024,27-06-2024,07-07-2024,08-08-2024,5.40,12,64.80,2

__________________________________________________ purchase_price __________________________________________________
count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,750mL,750,2,16.55,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,750,2,14.93,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,750mL,750,2,61.43,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,12.99,1500ml,1500,2,8.90,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,35.99,750mL,750,2,24.32,10754,PERFECTA WINES

__________________________________________________ sales __________________________________________________
count of records: 1048575

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,01-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,02-01-2024,750,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,03-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,08-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,09-01-2024,375,1,0.79,12546,JIM BEAM BRANDS COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,4,51.80,12.95,12-02-2024,750,2,0.45,2000,SOUTHERN WINE & SPIRITS NE
1048571,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,8,103.60,12.95,13-02-2024,750,2,0.90,2000,SOUTHERN WINE & SPIRITS NE
1048572,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,1,12.95,12.95,19-02-2024,750,2,0.11,2000,SOUTHERN WINE & SPIRITS NE
1048573,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,3,38.85,12.95,22-02-2024,750,2,0.34,2000,SOUTHERN WINE & SPIRITS NE
1048574,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,2,25.90,12.95,24-02-2024,750,2,0.22,2000,SOUTHERN WINE & SPIRITS NE

__________________________________________________ vendor __________________________________________________
count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,04-01-2024,8124,21-12-2023,16-02-2024,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,07-01-2024,8137,22-12-2023,21-02-2024,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,09-01-2024,8169,24-12-2023,16-02-2024,5,106.60,4.61,None
3,480,BACARDI USA INC,12-01-2024,8106,20-12-2023,05-02-2024,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,07-01-2024,8170,24-12-2023,12-02-2024,1935,15527.25,429.20,None
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,06-01-2025,13626,21-12-2024,10-02-2025,90,1563.00,8.60,None
5539,9625,WESTERN SPIRITS BEVERAGE CO,10-01-2025,13661,23-12-2024,18-02-2025,4617,37300.48,186.50,None
5540,3664,WILLIAM GRANT & SONS INC,02-01-2025,13643,22-12-2024,04-02-2025,9848,202815.78,932.95,None
5541,9815,WINE GROUP INC,03-01-2025,13602,20-12-2024,08-02-2025,24747,149007.56,819.54,None
5542,90058,ZORVINO VINEYARDS,05-01-2025,13574,18-12-2024,12-02-2025,437,3608.11,16.60,None

__________________________________________________ vendor_sales_summary __________________________________________________
count of records: 8512

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,1750.0,36.99,60320,1584606.40,344712.22,64889.97,9578.0,17598.14,68601.68,-1239894.18,-3.596897,0.006044,0.217538
1,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,1750.0,22.99,96073,1553500.41,444810.74,43304.31,20226.0,37163.76,257032.07,-1108689.67,-2.492498,0.013020,0.286328
2,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,1750.0,28.99,62385,1446708.15,275162.97,52289.50,9203.0,16909.12,144929.24,-1171545.18,-4.257641,0.006361,0.190199
3,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,1750.0,24.99,75385,1375022.40,288135.11,48202.30,11189.0,20557.97,123780.22,-1086887.29,-3.772145,0.008137,0.209549
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,1750.0,29.99,58783,1286759.87,357759.17,52774.51,11883.0,21833.58,257032.07,-929000.70,-2.596721,0.009235,0.278031
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8507,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,750.0,4.99,2,2.64,5.97,5.97,3.0,0.33,27100.41,3.33,0.557789,1.136364,2.261364
8508,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,50.0,0.49,6,2.34,62.72,0.98,128.0,6.72,50293.62,60.38,0.962691,54.700855,26.803419
8509,9815,WINE GROUP INC,22407,Three Wishes Chard,2.25,750.0,3.29,1,2.25,3.29,3.29,1.0,0.11,27100.41,1.04,0.316109,0.444444,1.462222
8510,3960,DIAGEO NORTH AMERICA INC,3775,Smirnoff Sorbet Pine/Coconut,0.73,50.0,0.99,1,0.73,0.00,0.00,0.0,0.00,257032.07,-0.73,-inf,0.000000,0.000000
8511,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,50.0,0.99,1,0.71,80.19,29.70,81.0,4.21,38994.78,79.48,0.991146,114.084507,112.943662

In [6]:
vendor = pd.read_sql('SELECT * FROM vendor', conn)

In [7]:
vendor['PONumber'].nunique()

5543

In [8]:
import pandas as pd

sales = pd.read_csv(r'C:\Users\shiva\OneDrive\Desktop\vendor_analysis\data6\sales.csv')  # replace with actual path
print(sales.columns)

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [9]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
58          3741.12     2753.88            288
60          1358.76     1086.01            124
61           335.76       27.98             24
62          6552.38     5342.68            162
63          5552.69     4526.93            131
...             ...         ...            ...
90084         63.98       63.98              2
90085         73.98       36.99              2
90086         51.99       51.99              1
90087        469.99      469.99              1
90089       3239.73      599.95             27

[7658 rows x 3 columns]

The purchase table contains actul purchase data ,including the date of purchase,products(brands) purchased by vendor ,the amount paid (in dollars ),
and the quantity purchased.
* The purchase price column is derived from the purchase_price table,which provides  product-wise actual and purchse  price. The combination of vendor and brand is unique in this table.
* The vendor_invoice table aggregates data from the purchase ttable,summerizing quantity and dollar amounts, alongg with an additional column for freight.This table maintains uniueness based on vendor and PO NUMber.
* The sales table capture actual sales transctions,detailling the brandds purchased by vendors,the quantity sold, the selling price, and the revenue eearned.

# as the data that we need for analysis is distributed in different tables,we need to create a summmary table containing
* purchase transctions made by vendor
* sales transction data
* freight costs for each vendor
* actul product price from vendor

In [10]:
vendor.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [11]:
freight_summary=pd.read_sql_query("""select VendorNumber,SUM(freight) as FreightCost
From vendor
Group By VendorNumber """,conn)
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [12]:
pd.read_sql_query("""select 
   p.VendorNumber,
   p.VendorName,
   p.Brand,
   p.PurchasePrice,
   pp.Volume,
   pp.Price as ActualPrice,
   SUM(p.Quantity) as TotalPurchasEQuantity,
   SUM(p.Dollars) as TotalPurchaseDollars
   FROM purchase p
   join purchase_price pp
   on p.Brand =pp .Brand
   where p.PurchasePrice > 0               
   GROUP BY p.VendorNumber,p.VendorNumber,p.Brand
   order by  TotalPurchaseDollars                                                                                        
                                                
                  """,conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchasEQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,3775,0.73,50,0.99,1,0.73
2,9815,WINE GROUP INC,22407,2.25,750,3.29,1,2.25
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
8507,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,58783,1286759.87
8508,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,75385,1375022.40
8509,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,62385,1446708.15
8510,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,96073,1553500.41
8511,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,60320,1584606.40

In [13]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [14]:
pd.read_sql_query("""SELECT
   VendorNo,
   Brand,
   SUM(SalesDollars) as TotalSalesDollars,  
   SUM(SalesPrice) as TotalSalesPrice,                                      
   SUM(SalesQuantity) as TotalSalesQuantity,
   SUM(ExciseTax) as TotalExciseTax
   from sales
   Group By VendorNo, Brand
   order by  TotalSalesDollars""",conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,3960,3303,0.99,0.99,1,0.05
2,9206,2773,0.99,0.99,1,0.05
3,9625,8872,0.99,0.99,1,0.05
4,3252,3933,1.98,0.99,2,0.10
...,...,...,...,...,...,...
7653,4425,3405,275162.97,52289.50,9203,16909.12
7654,17035,8068,288135.11,48202.30,11189,20557.97
7655,1128,1233,344712.22,64889.97,9578,17598.14
7656,3960,3545,357759.17,52774.51,11883,21833.58
7657,3960,4261,444810.74,43304.31,20226,37163.76

In [15]:
import time
start =time.time()
final_table = pd.read_sql_query("""
SELECT
    pp.VendorNumber,
    pp.Brand, 
    pp.Price,
    pp.PurchasePrice,  
    SUM(s.SalesQuantity) AS TotalSalesQuantity,                                                  
    SUM(s.SalesDollars) AS TotalSalesDollars,  
    SUM(s.SalesPrice) AS TotalSalesPrice,                                      
    SUM(s.ExciseTax) AS TotalExciseTax,
    SUM(vi.Quantity) AS TotalPurchaseQuantity,
    SUM(vi.Dollars) AS TotalPurchaseDollars,
    SUM(vi.Freight) AS TotalFreightCost
FROM purchase_price pp
JOIN sales s
    ON pp.VendorNumber = s.VendorNo AND pp.Brand = s.Brand
JOIN Vendor vi
    ON pp.VendorNumber = vi.VendorNumber 
GROUP BY 
    pp.VendorNumber, pp.Brand, pp.Price, pp.PurchasePrice
""",conn)
end=time.time()

In [16]:
vendor_sales_summary = pd.read_sql_query("""
WITH FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor
    GROUP BY VendorNumber
),
PurchaseSummary AS (
    SELECT
        p.VendorNumber,                            
        p.VendorName,
        p.Brand, 
        p.Description,                             
        p.PurchasePrice, 
        pp.Price AS ActualPrice,                              
        pp.Volume,                              
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars          
    FROM purchase p                                   
    JOIN purchase_price pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY 
        p.VendorNumber,
        p.VendorName,
        p.Brand, 
        p.Description,                             
        p.PurchasePrice, 
        pp.Price,
        pp.Volume
),
SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(SalesDollars) AS TotalSalesDollars,  
        SUM(SalesPrice) AS TotalSalesPrice,                                      
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales
    GROUP BY VendorNo, Brand                                                                                                         
)
SELECT
    ps.VendorNumber,                            
    ps.VendorName,
    ps.Brand, 
    ps.Description,                             
    ps.PurchasePrice, 
    ps.Volume,
    ps.ActualPrice,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesDollars,  
    ss.TotalSalesPrice,                                      
    ss.TotalSalesQuantity, 
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss                                       
    ON ps.VendorNumber = ss.VendorNo                                    
    AND ps.Brand = ss.Brand                                   
LEFT JOIN FreightSummary fs                                              
    ON ps.VendorNumber = fs.VendorNumber                                   
ORDER BY ps.TotalPurchaseDollars DESC
""", conn)

In [17]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,1750,36.99,60320,1584606.40,344712.22,64889.97,9578.0,17598.14,68601.68
1,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,1750,22.99,96073,1553500.41,444810.74,43304.31,20226.0,37163.76,257032.07
2,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,1750,28.99,62385,1446708.15,275162.97,52289.50,9203.0,16909.12,144929.24
3,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,1750,24.99,75385,1375022.40,288135.11,48202.30,11189.0,20557.97,123780.22
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,1750,29.99,58783,1286759.87,357759.17,52774.51,11883.0,21833.58,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8507,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,750,4.99,2,2.64,5.97,5.97,3.0,0.33,27100.41
8508,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,50,0.49,6,2.34,62.72,0.98,128.0,6.72,50293.62
8509,9815,WINE GROUP INC,22407,Three Wishes Chard,2.25,750,3.29,1,2.25,3.29,3.29,1.0,0.11,27100.41
8510,3960,DIAGEO NORTH AMERICA INC,3775,Smirnoff Sorbet Pine/Coconut,0.73,50,0.99,1,0.73,NaN,NaN,NaN,NaN,257032.07
8511,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,50,0.99,1,0.71,80.19,29.70,81.0,4.21,38994.78

In [18]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
Volume                    object
ActualPrice              float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalSalesQuantity       float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [19]:
vendor_sales_summary.isnull().sum()

VendorNumber                0
VendorName                  0
Brand                       0
Description                 0
PurchasePrice               0
Volume                      0
ActualPrice                 0
TotalPurchaseQuantity       0
TotalPurchaseDollars        0
TotalSalesDollars        1633
TotalSalesPrice          1633
TotalSalesQuantity       1633
TotalExciseTax           1633
FreightCost                 0
dtype: int64

In [20]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP          ', 'DIAGEO NORTH AMERICA INC   ',
       'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA          ',
       'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
       'ULTRA BEVERAGE COMPANY LLP ', 'PROXIMO SPIRITS INC.       ',
       'MAJESTIC FINE WINES        ', 'STOLI GROUP,(USA) LLC      ',
       'CAMPARI AMERICA            ', 'SAZERAC CO INC             ',
       'MOET HENNESSY USA INC      ', 'M S WALKER INC             ',
       'CONSTELLATION BRANDS INC   ', 'SAZERAC NORTH AMERICA INC. ',
       'REMY COINTREAU USA INC     ', 'SIDNEY FRANK IMPORTING CO  ',
       'WILLIAM GRANT & SONS INC   ', 'PALM BAY INTERNATIONAL INC ',
       'E & J GALLO WINERY         ', 'HEAVEN HILL DISTILLERIES   ',
       'CASTLE BRANDS CORP.        ', 'SOUTHERN WINE & SPIRITS NE ',
       'DISARONNO INTERNATIONAL LLC', 'EDRINGTON AMERICAS         ',
       'TRINCHERO FAMILY ESTATES   ', 'STE MICHELLE WINE ESTATES  ',
       'WINE GROUP INC             ', 'PERFECTA WINES             ',
       'LUXCO INC                  ', 'SHAW ROSS INT L IMP LTD    ',
       'TREASURY WINE ESTATES      ', 'MHW LTD                    ',
       'PHILLIPS PRODUCTS CO.      ', 'KOBRAND CORPORATION        ',
       'BANFI PRODUCTS CORP        ', 'STATE WINE & SPIRITS   ',
       'DIAGEO CHATEAU ESTATE WINES', 'CALEDONIA SPIRITS INC      ',
       'PINE STATE TRADING CO      ', 'VINEYARD BRANDS INC        ',
       'FABRIZIA SPIRITS LLC       ', 'LATITUDE BEVERAGE COMPANY  ',
       'DELICATO VINEYARDS INC     ', 'OLE SMOKY DISTILLERY LLC   ',
       'Serralles Usa LLC          ', 'DUGGANS DISTILLED PRODUCTS ',
       'KLIN SPIRITS LLC           ', 'LAIRD & CO                 ',
       'SEA HAGG DISTILLERY LLC    ', 'Dunn Wine Brokers          ',
       'WESTERN SPIRITS BEVERAGE CO', 'CHARLES JACQUIN ET CIE INC ',
       'FLAG HILL WINERY & VINEYARD', 'FREDERICK WILDMAN & SONS   ',
       'MCCORMICK DISTILLING CO    ', 'MARSALLE COMPANY           ',
       'MANGO BOTTLING INC         ', 'SWEET BABY VINEYARD        ',
       'AMERICAN VINTAGE BEVERAGE  ', 'LABELLE VYDS AND WINERY    ',
       'VRANKEN AMERICA            ', 'PREMIUM PORT WINES, INC.   ',
       'ATLANTIC IMPORTING COMPANY ', 'PREMIER DISTRIBUTORS       ',
       'Russian Standard Vodka     ', 'NICHE W & S                ',
       'WEIN BAUER INC             ', 'BULLY BOY DISTILLERS       ',
       'VINILANDIA USA             ', 'TAKARA SAKE USA INC        ',
       'PSP WINES ', 'ADAMBA IMPORTS INTL INC    ',
       'TY KU LLC                  ', 'MARTIGNETTI COMPANIES ',
       'ZORVINO VINEYARDS          ', 'SMOKY QUARTZ DISTILLERY LLC',
       'CRUSH WINES                ', 'TAMWORTH DISTILLING        ',
       'MOONLIGHT MEADERY          ', 'ALISA CARR BEVERAGES           ',
       'POVERTY LANE ORCHARDS      ', 'SEA BREEZE CELLARS LLC     ',
       'VINEXTRA INC               ', 'SWEETWATER FARM         ',
       'FORTUNE WINE BROKERS LLC   ', 'DJINN SPIRITS LLC          ',
       'JEWELL TOWNE VINEYARDS     ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'Circa Wines                ', 'HOOD RIVER DISTILLERS, Inc.',
       'INCREDIBREW INC            ', 'ALTAMAR BRANDS LLC         ',
       'CANDIA VINEYARDS           ', 'SURVILLE ENTERPRISES CORP  ',
       'TALL SHIP DISTILLERY LLC   ', 'BLACK PRINCE DISTILLERY INC',
       'STELLAR IMPORTING CO LLC   ', 'VINEDREA WINES LLC         ',
       'FULCHINO VINEYARD INC      ', 'STAR INDUSTRIES INC.       ',
       'WALPOLE MTN VIEW WINERY    ', 'HAUNTING WHISPER VYDS      ',
       'R.P.IMPORTS INC            ', 'THE PIERPONT GROUP LLC     ',
       'THE IMPORTED GRAPE LLC     ', 'BLACK ROCK SPIRITS LLC     ',
       'CENTEUR IMPORTS LLC        ', 'BRONCO WINE COMPANY        ',
       'PARK STREET IMPORTS LLC    ', 'APPOLO VINEYARDS LLC       ',
       'HIGHLAND WINE MERCHANTS LLC', 'MILTONS DISTRIBUTING CO    ',
       'SILVER MOUNTAIN CIDERS     ', 'FANTASY FINE WINES CORP    ',
       'CAPSTONE INTERNATIONAL     ', 'UNCORKED       '], dtype=object)

In [21]:
vendor_sales_summary['Description'].unique()

array(['Jack Daniels No 7 Black', 'Capt Morgan Spiced Rum',
       "Tito's Handmade Vodka", ..., 'Smirnoff Light Strawberry',
       'Concannon Glen Ellen Wh Zin', 'Three Wishes Chard'],
      shape=(7657,), dtype=object)

In [22]:
vendor_sales_summary['VendorNumber'].unique()

array([  1128,   3960,   4425,  17035,    480,  12546,   9165,   7245,
        10000,   8664,  11567,   8004,   8112,   9552,   1392,    660,
         7239,   3089,   3664,   6785,   3252,   3924,   1485,   2000,
         2555,   2561,   8892,   8673,   9815,  10754,   8352,   8320,
         9819,   6213,   9206,   4692,    516,    653,   1590,   1273,
         7153,   1587,   1655,   4950,   2242,   6359,  98450,   2496,
         4550,   4848,   8150,  17037,   9625,   4380,  17031,   9744,
         5992,   5455,   5270,  90056,   4466,  90032,   1601,   7240,
          388,   7154,  10050,   6355,   9622,   1189,  90024,   8920,
         7255,     60,   9260,  90058,  28750,  90047, 173357,   6215,
         1703,  90027,  17033,  90010, 172662,  90011,   2450,  17032,
            2,   1650,   3950,  90053,    105,  90046,   8735,  28776,
         2396,  12331,   9751,  90051,   8663,  90057,  90052,   7749,
        90037,  90017,   1265,   2876,   1003,   6830,    287,   3951,
         5612,  90026,  90033,   1439,   6280])

In [23]:
vendor_sales_summary['Volume']=vendor_sales_summary['Volume'].astype('float64')

In [24]:
vendor_sales_summary.fillna(0,inplace=True)

In [25]:
vendor_sales_summary['VendorName']=vendor_sales_summary['VendorName'].str.strip()

In [26]:
vendor_sales_summary['GrossProfit']=vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']

In [27]:
vendor_sales_summary['GrossProfit'].min()

np.float64(-1239894.18)

In [28]:
vendor_sales_summary['ProfitMargin'] =(vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars'])

In [29]:
vendor_sales_summary['StockTurnover'] =vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseDollars']

In [30]:
vendor_sales_summary['SalesPurchaseRatio']=vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [31]:
cursor=conn.cursor()

In [32]:
vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'Volume', 'ActualPrice', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'TotalSalesDollars', 'TotalSalesPrice',
       'TotalSalesQuantity', 'TotalExciseTax', 'FreightCost', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalesPurchaseRatio'],
      dtype='object')

In [34]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS vendor_sales_summary(
    VendorNumber INT,                            
    VendorName VARCHAR(100),
    Brand INT, 
    Description VARCHAR(100),                             
    PurchasePrice DECIMAL(10,2), 
    Volume DECIMAL(10,2),
    ActualPrice DECIMAL(10,2),
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars DECIMAL(15,2),
    TotalSalesDollars DECIMAL(15,2),  
    TotalSalesPrice DECIMAL(15,2),                                      
    TotalSalesQuantity INT, 
    TotalExciseTax DECIMAL(15,2),
    FreightCost DECIMAL(15,2),
    GrossProfit DECIMAL(15,2), 
    ProfitMargin DECIMAL(15,2),
    StockTurnover DECIMAL(15,2),
    SalesToPurchaseRatio DECIMAL(15,2),
    PRIMARY KEY (VendorNumber, Brand)
);
""")

In [35]:
pd.read_sql_query("select * from vendor_sales_summary",conn)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,1750.0,36.99,60320,1584606.40,344712.22,64889.97,9578.0,17598.14,68601.68,-1239894.18,-3.596897,0.006044,0.217538
1,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,1750.0,22.99,96073,1553500.41,444810.74,43304.31,20226.0,37163.76,257032.07,-1108689.67,-2.492498,0.013020,0.286328
2,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,1750.0,28.99,62385,1446708.15,275162.97,52289.50,9203.0,16909.12,144929.24,-1171545.18,-4.257641,0.006361,0.190199
3,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,1750.0,24.99,75385,1375022.40,288135.11,48202.30,11189.0,20557.97,123780.22,-1086887.29,-3.772145,0.008137,0.209549
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,1750.0,29.99,58783,1286759.87,357759.17,52774.51,11883.0,21833.58,257032.07,-929000.70,-2.596721,0.009235,0.278031
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8507,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,750.0,4.99,2,2.64,5.97,5.97,3.0,0.33,27100.41,3.33,0.557789,1.136364,2.261364
8508,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,50.0,0.49,6,2.34,62.72,0.98,128.0,6.72,50293.62,60.38,0.962691,54.700855,26.803419
8509,9815,WINE GROUP INC,22407,Three Wishes Chard,2.25,750.0,3.29,1,2.25,3.29,3.29,1.0,0.11,27100.41,1.04,0.316109,0.444444,1.462222
8510,3960,DIAGEO NORTH AMERICA INC,3775,Smirnoff Sorbet Pine/Coconut,0.73,50.0,0.99,1,0.73,0.00,0.00,0.0,0.00,257032.07,-0.73,-inf,0.000000,0.000000
8511,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,50.0,0.99,1,0.71,80.19,29.70,81.0,4.21,38994.78,79.48,0.991146,114.084507,112.943662

In [36]:
vendor_sales_summary.to_sql('vendor_sales_summary', conn, if_exists='replace',index=False)

8512